#!/usr/bin/env python3
"""
Phase 2C - Ranking (orders jobs by composite score)

Consumes the Phase 2C composite score file (output/phase2c_composite_scores.json)
and emits a ranked list of the same jobs, ordered deterministically.

INPUT (read-only, generated by phase2c_composite_score.py):
    output/phase2c_composite_scores.json

OUTPUT:
    output/phase2c_rankings.json

LOCKED RANKING POLICY (approved):
    Primary sort : composite_score DESCENDING
    Tie-break    : job_id ASCENDING (deterministic, stable)

RANKING IS A RANKING SIGNAL ONLY. It is NOT eligibility and NOT an application
decision. Every input job is ranked exactly once; no job is ever dropped or
filtered by tier, eligibility, or score. Ranking never blocks or rejects:
ranking_blocks is always false and ranking_rejection_reason is always null.

No new scoring policy is introduced here: ranks are derived purely from the
existing composite_score and the locked tie-break. Phase2B match_eligibility and
data_quality_status are carried through unchanged.

CRITICAL INVARIANTS (hard-validated in main + selftest):
    1. Every composite input job appears exactly once -> 20 ranks, no gaps.
    2. Ranks are exactly 1..N (1 = best / highest composite_score).
    3. composite_score is non-increasing across ranks (descending order).
    4. Equal composite_score values are ordered by ascending job_id.
    5. ranking_blocks == false and ranking_rejection_reason == null on all records.
    6. Deterministic output across runs.
"""
import json
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List

BASE_DIR = Path(__file__).resolve().parent
IN_COMPOSITE = BASE_DIR / "output" / "phase2c_composite_scores.json"
OUT = BASE_DIR / "output" / "phase2c_rankings.json"


def rank(composites: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Return the composite records ordered by descending composite_score with
    ascending job_id as the deterministic tie-break, annotated with `rank`
    (1 = highest). Never drops or filters any job."""
    ordered = sorted(composites, key=lambda c: (-c["composite_score"], c["job_id"]))

    ranked: List[Dict[str, Any]] = []
    for i, c in enumerate(ordered, start=1):
        ranked.append({
            "rank": i,
            "job_id": c["job_id"],
            "company_name": c["company_name"],
            "job_title": c["job_title"],
            "canonical_url": c.get("canonical_url"),
            "match_eligibility": c["match_eligibility"],
            "data_quality_status": c["data_quality_status"],
            "composite_score": c["composite_score"],
            "composite_confidence": c["composite_confidence"],
            "recommendation_tier": c["recommendation_tier"],
            "ranking_blocks": False,              # ranking NEVER blocks
            "ranking_rejection_reason": None,     # ranking NEVER rejects
        })
    return ranked


def main() -> None:
    composites: List[Dict[str, Any]] = json.load(open(IN_COMPOSITE))
    ranked = rank(composites)

    # --- invariant validation ------------------------------------------------
    assert len(ranked) == len(composites), "ranking must not drop any job"
    ids = [r["job_id"] for r in ranked]
    assert len(set(ids)) == len(ids), "duplicate job_id in ranking"
    assert set(ids) == {c["job_id"] for c in composites}, "ranking job_id set mismatch"
    assert [r["rank"] for r in ranked] == list(range(1, len(ranked) + 1)), "ranks not 1..N"

    # descending composite_score (non-increasing) across ranks
    scores = [r["composite_score"] for r in ranked]
    assert all(scores[i] >= scores[i + 1] for i in range(len(scores) - 1)), \
        "composite_score must be non-increasing across ranks"

    # tie-break: equal scores ordered by ascending job_id
    for i in range(len(ranked) - 1):
        if ranked[i]["composite_score"] == ranked[i + 1]["composite_score"]:
            assert ranked[i]["job_id"] < ranked[i + 1]["job_id"], "tie-break not ascending job_id"

    assert all(r["ranking_blocks"] is False and r["ranking_rejection_reason"] is None
               for r in ranked), "ranking must never block/reject"

    with open(OUT, "w") as f:
        json.dump(ranked, f, indent=2)

    tiers = Counter(r["recommendation_tier"] for r in ranked)
    by_elig = Counter(r["match_eligibility"] for r in ranked)

    print("=== PHASE 2C - RANKING (dry run) ===")
    print(f"Total ranked records       : {len(ranked)}")
    print(f"Ranks                     : 1..{len(ranked)}")
    print(f"  top (rank 1)            : {ranked[0]['company_name']} | {ranked[0]['job_title']} | score {ranked[0]['composite_score']}")
    print(f"  bottom (rank {len(ranked)}): {ranked[-1]['company_name']} | {ranked[-1]['job_title']} | score {ranked[-1]['composite_score']}")
    print("Tiers (carried through)   : " + ", ".join(f"{k}={v}" for k, v in tiers.items()))
    print("Eligibility (carried)     : " + ", ".join(f"{k}={v}" for k, v in by_elig.items()))
    print("Ranking blocks/rejects    : 0")
    print("Hard validation: 20 ranks, descending score, ascending job_id tie-break, "
          "blocks=false, rejections=null: PASS")
    print(f"\nWritten: {OUT}")


def selftest() -> None:
    """Unit tests covering the locked ranking behavior. In-memory only."""
    ok = True

    def check(label: str, cond: bool) -> None:
        nonlocal ok
        if not cond:
            ok = False
        print(f"{'OK ' if cond else 'FAIL'}  {label}")

    def rec(job_id: str, score: float) -> Dict[str, Any]:
        return {"job_id": job_id, "company_name": "C", "job_title": "T",
                "canonical_url": None, "match_eligibility": "ELIGIBLE",
                "data_quality_status": "COMPLETE", "composite_score": score,
                "composite_confidence": 1.0, "recommendation_tier": "MONITOR"}

    # simple descending order
    r = rank([rec("a", 0.5), rec("b", 0.9), rec("c", 0.1)])
    check("descending order", [x["job_id"] for x in r] == ["b", "a", "c"])
    check("ranks 1..3", [x["rank"] for x in r] == [1, 2, 3])

    # tie-break: equal score -> ascending job_id
    r = rank([rec("z", 0.5), rec("a", 0.5), rec("m", 0.5)])
    check("tie-break ascending job_id", [x["job_id"] for x in r] == ["a", "m", "z"])
    check("tie-break ranks still 1..3", [x["rank"] for x in r] == [1, 2, 3])

    # mixed: score dominates over tie-break
    r = rank([rec("a", 0.2), rec("z", 0.2), rec("m", 0.9)])
    check("score dominates tie-break", [x["job_id"] for x in r] == ["m", "a", "z"])

    # no job dropped
    src = [rec(str(i), float(i % 7) / 10.0) for i in range(20)]
    r = rank(src)
    check("20 in -> 20 out", len(r) == 20)
    check("all job_ids preserved", set(x["job_id"] for x in r) == set(x["job_id"] for x in src))
    check("no duplicate rank", len({x["rank"] for x in r}) == 20)

    # non-increasing scores across ranks
    scores = [x["composite_score"] for x in r]
    check("scores non-increasing", all(scores[i] >= scores[i + 1] for i in range(len(scores) - 1)))

    # never blocks/rejects
    check("never blocks", all(x["ranking_blocks"] is False for x in r))
    check("never rejects", all(x["ranking_rejection_reason"] is None for x in r))

    # carries eligibility/status through
    rec_e = rec("x", 0.3)
    rec_e["match_eligibility"] = "BLOCKED"
    rec_e["data_quality_status"] = "SUSPECT"
    out_e = rank([rec_e])[0]
    check("eligibility carried through", out_e["match_eligibility"] == "BLOCKED")
    check("status carried through", out_e["data_quality_status"] == "SUSPECT")

    assert ok, "Ranking self-test FAILED"
    print("\nRanking self-test: ALL PASS")


if __name__ == "__main__":
    selftest()
    main()
