#!/usr/bin/env python3
"""
Phase 2C - Application Decision Layer (which ranked jobs are worth applying to)

Consumes the Phase 2C ranking file (output/phase2c_rankings.json) and emits a
per-job application decision. It is a SEPARATE concept from eligibility, scoring,
and ranking (architecture concept #7): it decides which jobs are proposed as
application candidates, and it is gated by explicit human approval.

INPUT (read-only, generated by phase2c_ranking.py):
    output/phase2c_rankings.json

OUTPUT:
    output/phase2c_application_decisions.json

LOCKED DECISION POLICY (approved, 2026-08-11) - INCLUSIVE:
    CANDIDATE       : match_eligibility == ELIGIBLE AND
                      recommendation_tier in {RECOMMEND, CONSIDER}
    REVIEW          : match_eligibility == REVIEW        (human review required)
    NOT_RECOMMENDED : match_eligibility == BLOCKED
                      (or ELIGIBLE with tier == MONITOR, or any other case)

Decision priority is deterministic and evaluated in this order:
    1. match_eligibility == BLOCKED                 -> NOT_RECOMMENDED
    2. match_eligibility == REVIEW                  -> REVIEW
    3. recommendation_tier in {RECOMMEND, CONSIDER} and ELIGIBLE -> CANDIDATE
    4. else (e.g. ELIGIBLE + MONITOR)               -> NOT_RECOMMENDED

CRITICAL PROPERTIES
    - This is a PROPOSED SHORTLIST only. It NEVER auto-submits, sends emails,
      creates accounts, clicks Apply, or runs a browser. A human approval gate is
      required before any application preparation (Phase 3, ADR-010).
    - The decision is NOT an eligibility filter: every job stays visible. The
      decision never blocks or rejects a job (application_blocks is always false,
      application_rejection_reason is always null). BLOCKED/REVIEW here describe
      the application DECISION, and are derived from the existing Phase2B
      match_eligibility (which is carried through unchanged), not invented.
    - No job is dropped: 20 ranked inputs -> 20 decision outputs, ordered by rank.

CRITICAL INVARIANTS (hard-validated in main + selftest):
    1. 20 ranked jobs -> 20 decisions, ordered by rank (deterministic).
    2. No duplicate job_id; job_id set equals the ranking input.
    3. CANDIDATE requires ELIGIBLE and tier in {RECOMMEND, CONSIDER}.
    4. BLOCKED is always NOT_RECOMMENDED; REVIEW is always REVIEW.
    5. application_blocks == false and application_rejection_reason == null.
    6. match_eligibility / data_quality_status / recommendation_tier /
       composite_score / rank carried through unchanged.
    7. Deterministic output across runs.
"""
import json
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List

BASE_DIR = Path(__file__).resolve().parent
IN_RANKING = BASE_DIR / "output" / "phase2c_rankings.json"
OUT = BASE_DIR / "output" / "phase2c_application_decisions.json"

CANDIDATE_TIERS = {"RECOMMEND", "CONSIDER"}


def decide(rec: Dict[str, Any]) -> str:
    """Deterministic application decision for one ranked record."""
    elig = rec["match_eligibility"]
    tier = rec["recommendation_tier"]
    if elig == "BLOCKED":
        return "NOT_RECOMMENDED"
    if elig == "REVIEW":
        return "REVIEW"
    if elig == "ELIGIBLE" and tier in CANDIDATE_TIERS:
        return "CANDIDATE"
    return "NOT_RECOMMENDED"


def rationale(decision: str, rec: Dict[str, Any]) -> str:
    elig, tier = rec["match_eligibility"], rec["recommendation_tier"]
    if decision == "CANDIDATE":
        return f"ELIGIBLE and tier {tier}; proposed for application pending your approval"
    if decision == "REVIEW":
        return "match_eligibility=REVIEW; requires human review before application"
    return (f"not recommended: match_eligibility={elig}"
            + (f", tier={tier}" if tier else ""))


def make_decision(rec: Dict[str, Any]) -> Dict[str, Any]:
    decision = decide(rec)
    return {
        "rank": rec["rank"],
        "job_id": rec["job_id"],
        "company_name": rec["company_name"],
        "job_title": rec["job_title"],
        "canonical_url": rec.get("canonical_url"),
        # inputs to the decision (carried through unchanged)
        "match_eligibility": rec["match_eligibility"],
        "data_quality_status": rec["data_quality_status"],
        "composite_score": rec["composite_score"],
        "composite_confidence": rec["composite_confidence"],
        "recommendation_tier": rec["recommendation_tier"],
        # decision
        "application_decision": decision,
        "application_candidate": decision == "CANDIDATE",
        "decision_rationale": rationale(decision, rec),
        # decision is a proposal, never an eligibility block
        "application_blocks": False,
        "application_rejection_reason": None,
    }


def main() -> None:
    ranked: List[Dict[str, Any]] = json.load(open(IN_RANKING))
    # preserve rank order (already deterministic) for a readable shortlist
    decisions = [make_decision(r) for r in ranked]

    # --- invariant validation ------------------------------------------------
    assert len(decisions) == len(ranked), "must not drop any job"
    assert [d["rank"] for d in decisions] == [r["rank"] for r in ranked], "rank order changed"
    ids = [d["job_id"] for d in decisions]
    assert len(set(ids)) == len(ids), "duplicate job_id in decisions"
    assert set(ids) == {r["job_id"] for r in ranked}, "job_id set mismatch"

    # policy invariants
    for d in decisions:
        if d["application_decision"] == "CANDIDATE":
            assert d["match_eligibility"] == "ELIGIBLE", "CANDIDATE must be ELIGIBLE"
            assert d["recommendation_tier"] in CANDIDATE_TIERS, "CANDIDATE tier invalid"
        if d["match_eligibility"] == "BLOCKED":
            assert d["application_decision"] == "NOT_RECOMMENDED", "BLOCKED must be NOT_RECOMMENDED"
        if d["match_eligibility"] == "REVIEW":
            assert d["application_decision"] == "REVIEW", "REVIEW must stay REVIEW"
        assert d["application_blocks"] is False, "decision must never block"
        assert d["application_rejection_reason"] is None, "decision must never reject"
        assert d["application_candidate"] == (d["application_decision"] == "CANDIDATE")

    with open(OUT, "w") as f:
        json.dump(decisions, f, indent=2)

    by_decision = Counter(d["application_decision"] for d in decisions)
    candidates = [d for d in decisions if d["application_decision"] == "CANDIDATE"]

    print("=== PHASE 2C - APPLICATION DECISION (dry run) ===")
    print(f"Total decision records     : {len(decisions)}")
    print(f"Decision split             : " + ", ".join(f"{k}={v}" for k, v in
          sorted(by_decision.items())))
    print(f"Top candidate (rank 1)     : {candidates[0]['company_name']} | "
          f"{candidates[0]['job_title']} | {candidates[0]['composite_score']}")
    print("Application blocks/rejects : 0")
    print("NOTE: PROPOSED SHORTLIST ONLY - nothing is submitted. A human approval "
          "gate is required before any application preparation (ADR-010).")
    print("Hard validation: 20 -> 20, rank order preserved, CANDIDATE requires "
          "ELIGIBLE+RECOMMEND/CONSIDER, blocks=false, rejections=null: PASS")
    print(f"\nWritten: {OUT}")


def selftest() -> None:
    """Unit tests covering the locked decision policy. In-memory only."""
    ok = True

    def check(label: str, cond: bool) -> None:
        nonlocal ok
        if not cond:
            ok = False
        print(f"{'OK ' if cond else 'FAIL'}  {label}")

    def rec(job_id: str, elig: str, tier: str) -> Dict[str, Any]:
        return {"rank": 1, "job_id": job_id, "company_name": "C", "job_title": "T",
                "canonical_url": None, "match_eligibility": elig,
                "data_quality_status": "COMPLETE", "composite_score": 0.0,
                "composite_confidence": 1.0, "recommendation_tier": tier}

    # decision policy
    check("ELIGIBLE+RECOMMEND -> CANDIDATE", decide(rec("a", "ELIGIBLE", "RECOMMEND")) == "CANDIDATE")
    check("ELIGIBLE+CONSIDER -> CANDIDATE", decide(rec("b", "ELIGIBLE", "CONSIDER")) == "CANDIDATE")
    check("ELIGIBLE+MONITOR -> NOT_RECOMMENDED", decide(rec("c", "ELIGIBLE", "MONITOR")) == "NOT_RECOMMENDED")
    check("REVIEW -> REVIEW", decide(rec("d", "REVIEW", "RECOMMEND")) == "REVIEW")
    check("BLOCKED -> NOT_RECOMMENDED", decide(rec("e", "BLOCKED", "MONITOR")) == "NOT_RECOMMENDED")

    # output shape / invariants
    src = [
        rec("a", "ELIGIBLE", "RECOMMEND"),
        rec("b", "ELIGIBLE", "CONSIDER"),
        rec("c", "ELIGIBLE", "MONITOR"),
        rec("d", "REVIEW", "RECOMMEND"),
        rec("e", "BLOCKED", "MONITOR"),
    ]
    out = [make_decision(x) for x in src]
    check("5 in -> 5 out", len(out) == 5)
    check("CANDIDATE count = 2", sum(1 for x in out if x["application_decision"] == "CANDIDATE") == 2)
    check("REVIEW count = 1", sum(1 for x in out if x["application_decision"] == "REVIEW") == 1)
    check("NOT_RECOMMENDED count = 2", sum(1 for x in out if x["application_decision"] == "NOT_RECOMMENDED") == 2)
    check("candidate flag matches decision", all(
        x["application_candidate"] == (x["application_decision"] == "CANDIDATE") for x in out))
    check("never blocks", all(x["application_blocks"] is False for x in out))
    check("never rejects", all(x["application_rejection_reason"] is None for x in out))
    check("eligibility carried through", all(x["match_eligibility"] == y["match_eligibility"]
          for x, y in zip(out, src)))

    # rank-order preservation over a larger deterministic set
    big = [rec(str(i), "ELIGIBLE", "RECOMMEND" if i % 2 else "CONSIDER") for i in range(20)]
    for i, x in enumerate(big, start=1):
        x["rank"] = i
    big_out = [make_decision(x) for x in big]
    check("20 in -> 20 out", len(big_out) == 20)
    check("rank order preserved", [x["rank"] for x in big_out] == list(range(1, 21)))
    check("no duplicate job_id", len({x["job_id"] for x in big_out}) == 20)

    assert ok, "Application-decision self-test FAILED"
    print("\nApplication-decision self-test: ALL PASS")


if __name__ == "__main__":
    selftest()
    main()
